[Eth]
NetworkId = 1
SyncMode = "fast"

[Node]
DataDir = "C:\\path\\to\\geth\\data"  # Change this to your desired data directory
IPCPath = "geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net,web3"]